### ISSUE TITLE
Namespace collision with resque-scheduler

### ISSUE THREAD

**Issue by jasonbuehler** [mattgibson/resque-scheduler-web#1]
We're trying to add resque-scheduler-web to our app, but we're getting this error when we attempt to start up:
```
gems/resque-scheduler-web-0.0.1/lib/resque/scheduler/web/version.rb:2:in `<module:Resque>': Scheduler is not a module (TypeError)
```

This appears to be a collision with the class Resque::Scheduler in the resque-scheduler gem. 

MRI Ruby 2.0.0
resque-scheduler (2.5.5)
resque-scheduler-web (0.0.1)
resque-web (0.0.6)

**Comment by mattgibson** [comment]
Thanks for the report. This seems to be an issue with v2.5.5 of resque-scheduler, which defines `Resque::Scheduler` as a class, rather than a module. Are you able to upgrade to 3.0.0 or greater?

I will release a new version of the gem with updated dependencies so that bundler prevents this.

**Comment by mattgibson** [comment]
v0.0.2 is now up on RubyGems, so this error will no longer appear once you upgrade. It adds a dependency on resque-scheduler v4.0, so if there is an issue with upgrading that gem from v2.5.5, then please comment here with details.

**Comment by jasonbuehler** [comment]
Great, thanks Matt. Works like a charm.
