### ISSUE TITLE
RubyGems Build for undefined local variable or method `current_page'

### ISSUE THREAD

**Issue by zeeshangulzar** [mattgibson/resque-scheduler-web#6]
Hey Matt,

The issue i am facing was fixed in following merged PR #4, but we don't have latest build on ruby gems. Any idea when we can get the latest build on rubygems?

**Comment by mattgibson** [comment]
Oops - forgot to cut a release after that merge. Will sort that when I'm back home.

**Comment by zeeshangulzar** [comment]
@mattgibson Please if you can push latest build on RubyGems. I am eagerly waiting to fix this issue on my app.

**Comment by mattgibson** [comment]
Done. Any issues, let me know. Thanks for the feedback!
